### ISSUE TITLE
Bi-weekly Adoptium Community Call - August 18, 2021

### ISSUE THREAD

**Issue by adamfarley** [adoptium/adoptium#69]
**Time**

Wednesday August 18, 2021 3pm-4pm GMT (10am-11am EST/Ontario)

**Location**

https://bluejeans.com/956754991/2833?src=calendarLink

Add this recurring bi-weekly Adoptium Community Call to your calendar, if you wish. Available via the [Adoptium community calendar](https://calendar.google.com/calendar/u/1?cid=Y191YW5ub3VtczVobzBvbGhqazN1bGVjZGtiY0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t).

**Overall Purpose**

Mainly to make announcements regarding planned actions that affect the Adopt community
(Emphasis on non-test efforts, as those are covered in AQAvit call on opposite bi-weekly Wednesdays)

Secondary purposes include debate, discussion, and community socializing.

Call to be recorded for reference, and linked in this issue afterwards.

**Proposed Meeting Agenda** 

- July Release discussion
- Retrospective date? Rollover?
- AOB

**Comment by smlambert** [comment]
Meeting [recording link](https://bluejeans.com/s/i3rRsdOLb8V)

Minutes:
- July Release discussion
  - See https://github.com/adoptium/adoptium/issues/68 to get a view of the Temurin-compliance work
  - A streamlined set of images being produced and can be found in official docker repo: https://hub.docker.com/_/eclipse-temurin
- Retrospective date? Rollover?
  - https://github.com/adoptium/adoptium/issues/48 is our retrospective, let's use this community call in 2 weeks time for when to hold the public retrospective
  - a private Temurin-compliance retrospective will also be held to discuss issues/improvements that can happen relating to running/reporting TCKs
- AOB
  - will there be a respin for the MSI installer fix?  answer, likely yes, but there are a couple other issues (vendor name on 8) that may also get included in a respin so no date set
  - can we have a plan for moving to use aqa-tests JavaTestRunner branch for running TCKs for the Sept release?  (this relates to dropping some of the extra frameworks that are not needed to run TCKs, streamlining the automation and keeping only the pieces that are needed like Jck.java etc) - yes, lets create an aqa-tests issue to discuss any extra criteria we need to verify to transition to the more streamlined scripts.
  - is there a place for test and infra people to discuss common issues running JCKs?  yes, in the Temurin-compliance project, if its a candid discussion, otherwise we need to sanitize the issues being discussed and talk about a problem that can be extracted into a standalone test case outside of the licensed test material.  

Link to next meeting, which we will use as a July release retrospective is here: https://github.com/adoptium/adoptium/issues/48
